### ISSUE TITLE
can I get the data?

### ISSUE THREAD

**Issue by marcowus** [feimeng93/OnlineTimeInformedKinoMP#1]
i try to run this code,but thers is no data,can i get that?

**Comment by feimeng93** [comment]
Thank you for your interest. 
Our training and testing data can be generated when you run `cd Deepkoopman/train` `bash train.sh`. It will automatically run  https://github.com/feimeng93/OnlineTimeInformedKinoMP/blob/15554ec0ac2dc5e5f21f0dfa2afa2d27d632fcb8/Deepkoopman/Utility.py#L161 as long as there is no data exists. Thanks.
